# Trip type definitions for appointment abbreviations used in the xlsx schedule.
trip_type:
  HRm_:
    summary: "Binnendieze HRM"
    description: "Binnendieze; Historische route Molenstraat"
    first_shift_advance:
      - from: 2026-04-01
        to:   2026-04-30
        advance_minutes: 45
      - from: 2026-05-01
        to:   2026-06-30
        advance_minutes: 20
